name: GitHub Pages Astro CI

on:
  # Ativa o workflow toda vez que você fizer um push para a branch `main`
  # Usando um nome de branch diferente? Modifique `main` para o nome da sua branch
  push:
    branches: [main]
# Permite que esse workflow seja executado manualmente da aba "Actions" no GitHub.
  workflow_dispatch:

# Permite que este job clone o repositório e crie uma página de deploy
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install, build, and upload your site
        uses: withastro/action@v1
        with:
          node-version: 18  # Certifique-se de que a versão do Node é compatível
          package-manager: pnpm@latest  # Use a versão mais recente do pnpm ou especifique a versão que você precisa

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
